apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace : nexus
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: nexus-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

