apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-sql-pvc
  namespace : sonarqube
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: sonarqube-sql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

