apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-pvc
  namespace : harbor
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: harbor-registry-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
