apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-trivy-pvc
  namespace : harbor
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: harbor-trivy-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

