apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace : monitoring
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: prometheus-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

