apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: jenkins-pv
  resources:
    requests:
      storage: 10Gi
